### ISSUE TITLE
add mode to emit a warning if requested healpixel isn't part of the catalog

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/skyCatalogs#26]
A likely use case is where a CCD to be simulated is partially outside of any of the healpixels in the catalog.  In that case, a `KeyError` would be raised [here](https://github.com/LSSTDESC/skyCatalogs/blob/1d92bcf2e26c5aaafa2cbd817c35058a2f9fbc78/python/desc/skycatalogs/skyCatalogs.py#L332-L336).  It would be useful to have a mode where the `get_objects_by_hp` code emitted a warning if `hp not in self._hp_info` and returned an empty `ObjectList` instead of raising the exception.

**Comment by JoanneBogart** [comment]
This was addressed in commit [e033f1514cc4372fb78864e41f6dcaa847cdece6](https://github.com/LSSTDESC/skyCatalogs/commit/e033f1514cc4372fb78864e41f6dcaa847cdece6)
