### ISSUE TITLE
vignetted flats

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/skyCatalogs#92]
Various folks looking at ComCamSim simulations associated with ops-rehearsal-3 have requested flats with vignetting applied.  See the [slack thead.](https://lsstc.slack.com/archives/C06G49VRXB4/p1711573685003339?thread_ts=1711497253.993019&cid=C06G49VRXB4)

**Comment by JoanneBogart** [comment]
What does this have to do with skyCatalogs?

**Comment by jchiang87** [comment]
sorry!  It quite obviously has nothing to do with Sky catalogs.   I mean to open this in imSim.
